"""Auth module: tenancy root (clinics), identity (users), RBAC (roles,
permissions, role_permissions, permission_overrides), and the two tables
added during this module's implementation that extend
docs/schema/clinic_erp_schema.sql (otp_codes, user_sessions).

Written as raw SQL (not autogenerated) to stay a verbatim subset of the
hand-designed master schema at docs/schema/clinic_erp_schema.sql, which
remains the source of truth for the full multi-tenant design — this
migration only creates what the Auth module actually uses. Later modules
add their own tables/enums/policies in their own migrations.

Revision ID: 0001
Revises:
Create Date: 2026-09-02

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. Extensions & helper functions ---------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.execute(
        """
        CREATE OR REPLACE FUNCTION app_current_tenant_id() RETURNS uuid AS $$
          SELECT NULLIF(current_setting('app.current_tenant_id', true), '')::uuid;
        $$ LANGUAGE sql STABLE;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION app_is_platform_admin() RETURNS boolean AS $$
          SELECT COALESCE(NULLIF(current_setting('app.is_platform_admin', true), '')::boolean, false);
        $$ LANGUAGE sql STABLE;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
          NEW.updated_at = now();
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_update_delete() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'rows in % are append-only and cannot be % (attempted on id=%)',
            TG_TABLE_NAME, TG_OP, COALESCE(OLD.id::text, 'unknown');
          RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # --- 2. Enum types ------------------------------------------------------
    op.execute("CREATE TYPE clinic_status AS ENUM ('TRIAL','ACTIVE','SUSPENDED','CANCELLED')")
    op.execute("CREATE TYPE user_status AS ENUM ('INVITED','ACTIVE','INACTIVE','SUSPENDED')")
    op.execute("CREATE TYPE otp_purpose AS ENUM ('LOGIN')")

    # --- 3. Tenancy root: clinics --------------------------------------------
    op.execute(
        """
        CREATE TABLE clinics (
          id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          name        text NOT NULL,
          slug        text NOT NULL UNIQUE,
          timezone    text NOT NULL DEFAULT 'Asia/Kolkata',
          locale      text NOT NULL DEFAULT 'en-IN',
          gst_number  text,
          status      clinic_status NOT NULL DEFAULT 'TRIAL',
          created_at  timestamptz NOT NULL DEFAULT now(),
          updated_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )

    # --- 4. RBAC reference data: roles, permissions, role_permissions -------
    op.execute(
        """
        CREATE TABLE roles (
          id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          code        text NOT NULL UNIQUE,
          name        text NOT NULL,
          description text,
          created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE permissions (
          id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          code        text NOT NULL UNIQUE,
          module      text NOT NULL,
          description text,
          created_at  timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute(
        """
        CREATE TABLE role_permissions (
          id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          role_id       UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
          permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
          UNIQUE (role_id, permission_id)
        )
        """
    )

    # --- 5. Identity: users --------------------------------------------------
    op.execute(
        """
        CREATE TABLE users (
          id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          tenant_id     UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
          role_id       UUID NOT NULL REFERENCES roles(id),
          email         text,
          phone         text,
          password_hash text,
          status        user_status NOT NULL DEFAULT 'ACTIVE',
          mfa_enabled   boolean NOT NULL DEFAULT false,
          last_login_at timestamptz,
          created_at    timestamptz NOT NULL DEFAULT now(),
          updated_at    timestamptz NOT NULL DEFAULT now(),
          CHECK (email IS NOT NULL OR phone IS NOT NULL)
        )
        """
    )
    op.execute("CREATE UNIQUE INDEX ux_users_tenant_email ON users (tenant_id, lower(email)) WHERE email IS NOT NULL")
    op.execute("CREATE UNIQUE INDEX ux_users_tenant_phone ON users (tenant_id, phone) WHERE phone IS NOT NULL")

    # --- 6. permission_overrides ----------------------------------------------
    op.execute(
        """
        CREATE TABLE permission_overrides (
          id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          tenant_id     UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
          role_id       UUID REFERENCES roles(id),
          user_id       UUID REFERENCES users(id) ON DELETE CASCADE,
          permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
          granted       boolean NOT NULL,
          created_by    UUID REFERENCES users(id),
          created_at    timestamptz NOT NULL DEFAULT now(),
          updated_at    timestamptz NOT NULL DEFAULT now(),
          CHECK ((role_id IS NOT NULL)::int + (user_id IS NOT NULL)::int = 1)
        )
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_perm_override_role ON permission_overrides (tenant_id, role_id, permission_id) WHERE role_id IS NOT NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX ux_perm_override_user ON permission_overrides (tenant_id, user_id, permission_id) WHERE user_id IS NOT NULL"
    )

    # --- 7. otp_codes (added during Auth module implementation) --------------
    op.execute(
        """
        CREATE TABLE otp_codes (
          id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          tenant_id      UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
          user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          purpose        otp_purpose NOT NULL DEFAULT 'LOGIN',
          code_hash      text NOT NULL,
          attempt_count  int NOT NULL DEFAULT 0,
          expires_at     timestamptz NOT NULL,
          consumed_at    timestamptz,
          created_at     timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_otp_codes_user_active ON otp_codes (user_id, created_at) WHERE consumed_at IS NULL")

    # --- 8. user_sessions (opaque refresh tokens; added during Auth module) --
    op.execute(
        """
        CREATE TABLE user_sessions (
          id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          tenant_id          UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
          user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          refresh_token_hash text NOT NULL UNIQUE,
          device_label       text,
          ip_address         text,
          user_agent         text,
          issued_at          timestamptz NOT NULL DEFAULT now(),
          expires_at         timestamptz NOT NULL,
          revoked_at         timestamptz
        )
        """
    )
    op.execute("CREATE INDEX ix_user_sessions_user_active ON user_sessions (user_id) WHERE revoked_at IS NULL")

    # --- 9. updated_at triggers (master-data tables only) ---------------------
    for table in ("clinics", "users", "permission_overrides"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )

    # --- 10. Row-Level Security -------------------------------------------------
    op.execute("ALTER TABLE clinics ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE clinics FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON clinics
          USING (id = app_current_tenant_id() OR app_is_platform_admin())
          WITH CHECK (id = app_current_tenant_id() OR app_is_platform_admin())
        """
    )

    for table in ("users", "permission_overrides", "otp_codes", "user_sessions"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (tenant_id = app_current_tenant_id() OR app_is_platform_admin())
              WITH CHECK (tenant_id = app_current_tenant_id() OR app_is_platform_admin())
            """
        )
    # roles, permissions, role_permissions intentionally have NO RLS — see
    # docs/schema/clinic_erp_schema.sql section 16c (global reference data,
    # readable by every tenant connection to resolve RBAC).

    # --- 11. Seed data: the 8 system roles + a representative permission set -
    op.execute(
        """
        INSERT INTO roles (code, name) VALUES
          ('OWNER',          'Clinic Owner'),
          ('DOCTOR',         'Doctor'),
          ('RECEPTIONIST',   'Receptionist'),
          ('NURSE',          'Nurse'),
          ('LAB_STAFF',      'Lab Staff'),
          ('PHARMACY_STAFF', 'Pharmacy Staff'),
          ('OTHER_STAFF',    'Other Staff'),
          ('PATIENT',        'Patient')
        """
    )
    op.execute(
        """
        INSERT INTO permissions (code, module, description) VALUES
          ('clinic.manage_settings',     'tenancy',       'Manage clinic profile, branding, and branches'),
          ('staff.manage',               'identity',      'Invite/manage staff accounts and role assignments'),
          ('doctor.manage_own_profile',  'identity',      'Doctor edits their own profile/working hours'),
          ('patients.register',          'patients',      'Register new patients / edit demographics'),
          ('patients.view_demographics', 'patients',      'View patient demographic info (not full EMR)'),
          ('patients.view_emr',          'patients',      'View full clinical record'),
          ('appointments.manage',        'appointments',  'Book/reschedule/cancel appointments for any patient'),
          ('appointments.book_own',      'appointments',  'Patient books/cancels their own appointment'),
          ('checkin.manage',             'queue',         'Check in patients, manage walk-ins'),
          ('queue.manage',               'queue',         'Manage queue/token status'),
          ('vitals.record',              'vitals',        'Record a vitals reading'),
          ('consultation.manage',        'clinical',      'Create/edit consultation, diagnosis, clinical notes'),
          ('prescription.manage',        'clinical',      'Issue e-prescriptions'),
          ('billing.manage',             'billing',       'Create/edit invoices'),
          ('billing.view_own',           'billing',       'Patient views own invoices'),
          ('payments.record',            'billing',       'Record payments against an invoice'),
          ('pharmacy.manage_catalog',    'pharmacy',      'Manage medicine catalog and stock'),
          ('pharmacy.dispense',          'pharmacy',      'Dispense prescriptions / process OTC sales'),
          ('lab.manage_catalog',         'laboratory',    'Manage lab test catalog'),
          ('lab.order',                  'laboratory',    'Order lab tests'),
          ('lab.enter_results',          'laboratory',    'Enter/finalize lab results'),
          ('inventory.manage',           'inventory',     'Manage general (non-pharmacy) inventory'),
          ('expenses.manage',            'finance',       'Record and manage expenses'),
          ('crm.manage',                 'crm',           'Manage leads and follow-ups'),
          ('communications.send',        'communications','Send patient/lead communications'),
          ('dashboard.view',             'analytics',     'View owner dashboard, analytics, and reports'),
          ('audit.view',                 'security',      'View the tenant audit log'),
          ('branches.manage',            'tenancy',       'Create/edit branches')
        """
    )
    op.execute(
        """
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p WHERE (r.code, p.code) IN (
          ('OWNER','clinic.manage_settings'), ('OWNER','staff.manage'), ('OWNER','patients.register'),
          ('OWNER','patients.view_emr'), ('OWNER','appointments.manage'), ('OWNER','checkin.manage'),
          ('OWNER','queue.manage'), ('OWNER','vitals.record'), ('OWNER','billing.manage'),
          ('OWNER','payments.record'), ('OWNER','pharmacy.manage_catalog'), ('OWNER','pharmacy.dispense'),
          ('OWNER','lab.manage_catalog'), ('OWNER','lab.order'), ('OWNER','lab.enter_results'),
          ('OWNER','inventory.manage'), ('OWNER','expenses.manage'), ('OWNER','crm.manage'),
          ('OWNER','communications.send'), ('OWNER','dashboard.view'), ('OWNER','audit.view'),
          ('OWNER','branches.manage'),

          ('DOCTOR','doctor.manage_own_profile'), ('DOCTOR','patients.view_emr'),
          ('DOCTOR','patients.view_demographics'), ('DOCTOR','appointments.manage'),
          ('DOCTOR','vitals.record'), ('DOCTOR','consultation.manage'), ('DOCTOR','prescription.manage'),
          ('DOCTOR','lab.order'), ('DOCTOR','billing.view_own'),

          ('RECEPTIONIST','patients.register'), ('RECEPTIONIST','patients.view_demographics'),
          ('RECEPTIONIST','appointments.manage'), ('RECEPTIONIST','checkin.manage'),
          ('RECEPTIONIST','queue.manage'), ('RECEPTIONIST','billing.manage'),
          ('RECEPTIONIST','payments.record'), ('RECEPTIONIST','crm.manage'),
          ('RECEPTIONIST','communications.send'),

          ('NURSE','patients.view_demographics'), ('NURSE','vitals.record'), ('NURSE','queue.manage'),

          ('LAB_STAFF','lab.order'), ('LAB_STAFF','lab.enter_results'),

          ('PHARMACY_STAFF','pharmacy.manage_catalog'), ('PHARMACY_STAFF','pharmacy.dispense'),

          ('PATIENT','appointments.book_own'), ('PATIENT','billing.view_own')
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS user_sessions")
    op.execute("DROP TABLE IF EXISTS otp_codes")
    op.execute("DROP TABLE IF EXISTS permission_overrides")
    op.execute("DROP TABLE IF EXISTS role_permissions")
    op.execute("DROP TABLE IF EXISTS users")
    op.execute("DROP TABLE IF EXISTS permissions")
    op.execute("DROP TABLE IF EXISTS roles")
    op.execute("DROP TABLE IF EXISTS clinics")

    op.execute("DROP FUNCTION IF EXISTS prevent_update_delete()")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
    op.execute("DROP FUNCTION IF EXISTS app_is_platform_admin()")
    op.execute("DROP FUNCTION IF EXISTS app_current_tenant_id()")

    op.execute("DROP TYPE IF EXISTS otp_purpose")
    op.execute("DROP TYPE IF EXISTS user_status")
    op.execute("DROP TYPE IF EXISTS clinic_status")
